CREATE TABLE matriculas(
    id BIGINT NOT NULL AUTO_INCREMENT,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    estudante_id BIGINT NOT NULL,
    turma_id BIGINT NOT NULL,

    PRIMARY KEY(id),
    CONSTRAINT MATRICULA_FK_ESTUDANTE FOREIGN KEY(estudante_id) REFERENCES estudantes(id),
    CONSTRAINT MATRICULA_FK_TURMA FOREIGN KEY(turma_id) REFERENCES turmas(id)
);
